#pragma once
#include <stdexcept>

namespace info {
const std::string TEXT =
    "=== Program Interaction Protocol ===\n"
    "1. The first word in the input is ignored—it represents the executable file name.\n"
    "2. Specify the input file path in the format: C:/Users/Username/Downloads/image.bmp\n"
    "3. The output file path should follow the same format as the input file.\n"
    "\n"
    "=== Filter Usage ===\n"
    "Each filter is applied using the format:\n"
    "  -{filter_name} {arg1} {arg2} ...\n"
    "\n"
    "=== Available Filters ===\n"
    "\n"
    "-gs      Convert the image to grayscale.\n"
    "         Example: -gs\n"
    "\n"
    "-crop    Crop the image to the specified width and height.\n"
    "         Usage: -crop <width> <height>\n"
    "         Example: -crop 800 600\n"
    "\n"
    "-sharp   Enhance image sharpness.\n"
    "         Example: -sharp\n"
    "\n"
    "-edge    Highlight edges with a specified threshold.\n"
    "         Usage: -edge <threshold>\n"
    "         Example: -edge 0.5\n"
    "\n"
    "-blur    Apply a blur effect with a given radius.\n"
    "         Usage: -blur <radius>\n"
    "         Example: -blur 5\n"
    "\n"
    "-vshrink Reduce the image height while maintaining proportions.\n"
    "         Usage: -vshrink <new_height>\n"
    "         Example: -vshrink 300\n"
    "\n"
    "-hshrink Reduce the image width while maintaining proportions.\n"
    "         Usage: -hshrink <new_width>\n"
    "         Example: -hshrink 400\n"
    "\n"
    "-shrink  Resize the image to new dimensions.\n"
    "         Usage: -shrink <new_height> <new_width>\n"
    "         Example: -shrink 300 400\n"
    "\n"
    "=== Example: Applying Multiple Filters ===\n"
    "image_processor input.bmp output.bmp -gs -crop 500 400 -sharp -blur 1.5 -shrink 300 400\n";
}  // namespace info